# Generated by Django 3.0.4 on 2020-03-31 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('likes', models.ManyToManyField(related_name='users_that_liked', to=settings.AUTH_USER_MODEL)),
                ('mainPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.Post')),
                ('shared', models.ManyToManyField(related_name='users_that_shared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
