# Generated by Django 3.0.4 on 2020-04-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postings', '0002_auto_20200331_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rePost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retuits', to='postings.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='mainPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postings.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='sharedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
