# Generated by Django 3.0.4 on 2020-04-01 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postings', '0002_auto_20200331_0122'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postsLiked',
            field=models.ManyToManyField(blank=True, related_name='postsLiked', to='postings.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postsShared',
            field=models.ManyToManyField(blank=True, related_name='postsShared', to='postings.Post'),
        ),
    ]
