# Generated by Django 3.0.4 on 2020-04-01 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20200401_1631'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200331_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postsLiked',
            field=models.ManyToManyField(blank=True, related_name='likedby', to='postings.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postsShared',
            field=models.ManyToManyField(blank=True, related_name='sharedby', to='postings.Post'),
        ),
    ]
